#=============================================================
#             TvT Event Engine (Team vs Team)
#=============================================================

# Enable/Disable TvTEvent System
TvTEventEnabled = True

# Times TvT will occur (24h format).
TvTEventInterval = 04:00,10:00,16:00,22:00

# Registration timer from start of event (in minutes).
TvTEventParticipationTime = 5

# Event running time (in minutes).
TvTEventRunningTime = 5

# Location name of EventManager.
TvTNpcLocName = Giran Town

# TvT Event NPC (create a custom npc of type L2EventManager).
TvTEventParticipationNpcId = 50310

# Location for TvTEvent NPC to spawn in form x,y,z,[heading]
TvTEventParticipationNpcCoordinates = 82840,148648,-3416

# TvT Event Participation Fee (itemId, number). Fee is not returned.
# Example: 57,100000
# Default = 0,0
TvTEventParticipationFee = 0,0

# Reward for winning team.
# Example: TvTEventRewardWinners = itemId,min,max,chance;itemId,min,max,chance;itemId,min,max,chance;...
TvTEventRewardWinners = 9501,200,250;9555,5,5;9552,5,5;9509,100,200;9999,3,5;

# Reward for loser team.
# Example: TvTEventRewardLosers = itemId,min,max,chance;itemId,min,max,chance;itemId,min,max,chance;...
TvTEventRewardLosers = 9501,100,150;9555,2,2;9552,2,2;9509,80,120;9999,2,3;

# Min/Max amount of players allowed in each team.
TvTEventMinPlayersInTeams = 1
TvTEventMaxPlayersInTeams = 300

# Min/Max level of players that may join the event.
TvTEventMinPlayerLevel = 61
TvTEventMaxPlayerLevel = 80

# Repsawn and exit delay timers (in seconds).
TvTEventRespawnTeleportDelay = 3
TvTEventStartLeaveTeleportDelay = 3

# First Team - Name, Start/Death x,y,z location. BLUE
TvTEventTeam1Name = *PCC*
TvTEventTeam1Coordinates = 84312,255752,-11664

# Second Team - Name, Start/Death x,y,z location. RED
TvTEventTeam2Name = *CV*
TvTEventTeam2Coordinates = 86968,258296,-11664

# TvTEvent Rules
TvTEventTargetTeamMembersAllowed = False
TvTEventScrollsAllowed = False
TvTEventPotionsAllowed = False
TvTEventSummonByItemAllowed = False

# Door ID's to open on TvT finish.
TvTDoorsToOpen = 24190001;24190002;24190003;24190004
# Door ID's to open on TvT start.
TvTDoorsToClose = 24190001;24190002;24190003;24190004

# Should both teams get reward if there's a tie?
TvTRewardTeamTie = False

# Participant's effects handling on teleport/death.
# Effects lasting through death never removed.
# 0 - always remove all effects.
# 1 - remove all effects only during port to event (noblesse blessing can be used)
# 2 - never remove any effect
# Default: 0
TvTEventEffectsRemoval = 2

# Fighter-class participants will be buffed with those buffs each respawn
# Format: skill1Id,skill1Level;skill2Id,skill2Level;...
# Example: 1504,1;1501,1;1502,1;1499,1
TvTEventFighterBuffs = 

# Mage-class participants will be buffed with those buffs each respawn
# Format: skill1Id,skill1Level;skill2Id,skill2Level;...
# Example: 1504,1;1500,1;1501,1;1085,3
TvTEventMageBuffs = 

# Enabling this option will not be possible to register for the event with the specified number of Box.
# Default: True
TvTEventMultiBoxEnable = True
# Box number allowed inside the event.
# Default: 1
TvTEventNumberBoxRegister = 2

# Define if TvTEvent will reward everyone or only players who have killed 1 or more.
# Default: False
TvTRewardOnlyKillers = True

# Method to show player's kill on the TvT event.
# Choose "pm" for an automatic personal message to the player team.
# Example: "Player1: I have killed Player2 !".
# Put "title" for an automatic title that counts the player's kills.
# Example: "Kills: number" (title will be restored at the event end).
# Put "pmtitle" for both methods (pmtitle and title).
# Default: title
TvTEventOnKill = title

# ID of classes that are not allowed to join the tvt
TvTDisabledForClasses = 16,97,30,105,43,112

# TvT Time BOX Invite
# Default: False
AllowDlgTvTInvite = False

# Enabling rewarding disconected players
# Default: False
TvTRewardNoCarrierPlayers = True

# TvT Peace Zone attack
# Default: False
EnableTvTPeaceZoneAttack = True

# TvT World Instance System
# Default: False
EnableTvTInstance = True
# TvT World Instance ID
TvTInstanceId = 5
