#=============================================================
#                   Time Instance Zone
#=============================================================

# Time Zone Event Enabled.
TimeInstanceEnabled = False

# Duration time that the player can stay in the area (in minutes)
# 60 minutos por jogador
TimeInstancePlayerTime = 60

# Warnings on screen
TimeInstanceScreenMessage = True

# Allow players to farm in party
TimeInstanceAllowParty = True

# Time Zone flag on enter
TimeInstanceFlagZone = False

# Classes not allowed to farm on Time Instance
TimeInstanceBlockClassesIds = 97,105,112

# Time Instance item to join on area
TimeInstanceItemIdToAcess = 9517

# Reward after player kill this number of mobs
TimeInstanceMobsToReward = 200

# Time Zone mobs ids
TimeInstanceMobsIds = 10516

# Time Zone rewards
# Format: itemId,count,chance(%);itemId,count,(chance(%)(optional));....
TimeInstanceDropItemsIds = 57,3000000,100;9552,1,30;9555,1,30;

# Time Zone teleport Spots
TimeInstanceAreaLocSpot1 = -16376,-47464,-10816
TimeInstanceAreaLocSpot2 = -16392,-50888,-11008
TimeInstanceAreaLocSpot3 = -16376,-47464,-10816
TimeInstanceAreaLocSpot4 = -16392,-50888,-11008
