#=============================================================
#                  CUSTOM ITEMS CLICKS
#=============================================================
# Give Augumentation skill
CustomItemAugumentation = 9998
# Give a Roulette item reward
CustomItemRoulette = 9999
#=============================================================
#                 TERRITORY WAR
#=============================================================
# Activate the spear war for territories. 
# Remember to correctly configure the event xml in "data\xml\territorywar.xml"
# Default: False
EnableTerritoryWar = False
# Default: 50015 Npc type "HolyThing".
TerritoryWarNpcId = 50027
# Default: 20 minutes (1200000)
TerritoryWarEventDuration = 1200000
# If the rest of the number is equal to 0, the remaining time will be announced
# Default: 5 minutes
TerritoryWarEventCountDown = 5
# Active buff for players in radius 
# Default: 0 (Disable)
TerritoryWarEventBuffId = 5123
# Delay in seconds for buff
# Default: 30 seconds
TerritoryWarEventBuffDelay = 30
# Radius to buff
# Default: 450
TerritoryWarEventBuffRadius = 450
# Finished Event on the first clan has take the Npc?
# Default: False
TerritoryWarEventFinishedOnTakeNpc = True
# Allow Radar on open Mini Map?
# Default: False
TerritoryWarEventAllowRadar = True
# Drop Rate for clan domination of the territory
# Default: 3.
TerritoryWarEventDropRate = 3